# Generated by Django 4.1.7 on 2023-05-20 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_author_rate_alter_comment_rate_alter_post_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='news.PostCategory', to='news.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='heading',
            field=models.CharField(max_length=255, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='property',
            field=models.CharField(choices=[('N', 'Новость'), ('A', 'Статья')], max_length=1, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rate',
            field=models.SmallIntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
