# Generated by Django 4.2.4 on 2023-08-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_post_heading_en_us_post_heading_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_en_us',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=models.TextField(null=True, verbose_name='Содержание'),
        ),
    ]
